name: Deploy to Amazon S3

on:
  push:
    branches: ['main']

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test

    env:
      # Test server env vars
      NODE_ENV: test
      JWT_SECRET: testsecret
      POSTGRES_DB: chat-app-db
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

      # Client env vars
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout client
        uses: actions/checkout@v3
        with:
          path: client

      - name: Clean install dependencies and build client
        run: |
          npm ci
          npm run build

      - name: Checkout server
        uses: actions/checkout@v3
        with:
          repository: shaundnz/chat-group-server
          path: server

      - name: Clean install dependencies and build server
        working-directory: ./server
        run: |
          npm ci
          npm run build

      - name: Setup database
        working-directory: ./server
        run: npm run database:reset -- TestSeeder

      - name: Start server
        working-directory: ./server
        run: |
          npm run start:prod &
          sleep 5 &&
          curl $VITE_API_BASE_URL/health-check -I

      - name: Run unit tests
        run: npm run test:unit

      - name: Run E2E tests
        run: npm run test:integration

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    env:
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean install dependencies and build client
        run: |
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          private: true
          delete-removed: true
